import { Play } from '@/types/play'

const PICK_AND_ROLL: Play = {
  id: 'demo-pnr',
  name: 'Pick & Roll',
  keyframes: [
    {
      id: 'pnr-1',
      description: 'Posición inicial. El 1 tiene el balón en la cima del arco, el 5 va a subir a poner la cortina.',
      ballPosition: { x: 50, y: 72 },
      positions: [
        { playerId: 'o1', x: 50, y: 72 },
        { playerId: 'o2', x: 15, y: 58 },
        { playerId: 'o3', x: 85, y: 58 },
        { playerId: 'o4', x: 15, y: 36 },
        { playerId: 'o5', x: 78, y: 36 },
        { playerId: 'd1', x: 50, y: 65 },
        { playerId: 'd2', x: 15, y: 52 },
        { playerId: 'd3', x: 85, y: 52 },
        { playerId: 'd4', x: 20, y: 30 },
        { playerId: 'd5', x: 74, y: 30 },
      ],
    },
    {
      id: 'pnr-2',
      description: 'El 5 sube a poner la cortina sobre el defensor del 1. El defensor del 5 lo sigue.',
      ballPosition: { x: 50, y: 72 },
      positions: [
        { playerId: 'o1', x: 50, y: 72 },
        { playerId: 'o2', x: 10, y: 55 },
        { playerId: 'o3', x: 90, y: 55 },
        { playerId: 'o4', x: 15, y: 36 },
        { playerId: 'o5', x: 55, y: 62 },
        { playerId: 'd1', x: 50, y: 66 },
        { playerId: 'd2', x: 10, y: 50 },
        { playerId: 'd3', x: 90, y: 50 },
        { playerId: 'd4', x: 20, y: 30 },
        { playerId: 'd5', x: 60, y: 56 },
      ],
    },
    {
      id: 'pnr-3',
      description: 'El 1 usa la cortina y sale por izquierda. El 5 inicia el roll hacia el aro.',
      ballPosition: { x: 38, y: 62 },
      positions: [
        { playerId: 'o1', x: 38, y: 62 },
        { playerId: 'o2', x: 10, y: 48 },
        { playerId: 'o3', x: 90, y: 48 },
        { playerId: 'o4', x: 15, y: 36 },
        { playerId: 'o5', x: 50, y: 48 },
        { playerId: 'd1', x: 42, y: 58 },
        { playerId: 'd2', x: 10, y: 44 },
        { playerId: 'd3', x: 90, y: 44 },
        { playerId: 'd4', x: 20, y: 30 },
        { playerId: 'd5', x: 52, y: 40 },
      ],
    },
    {
      id: 'pnr-4',
      description: '¡El 1 pasa al 5 que llegó solo al aro! La defensa no puede cubrir los dos.',
      ballPosition: { x: 48, y: 20 },
      positions: [
        { playerId: 'o1', x: 30, y: 52 },
        { playerId: 'o2', x: 10, y: 42 },
        { playerId: 'o3', x: 90, y: 42 },
        { playerId: 'o4', x: 15, y: 36 },
        { playerId: 'o5', x: 48, y: 20 },
        { playerId: 'd1', x: 34, y: 48 },
        { playerId: 'd2', x: 10, y: 38 },
        { playerId: 'd3', x: 90, y: 38 },
        { playerId: 'd4', x: 20, y: 30 },
        { playerId: 'd5', x: 50, y: 32 },
      ],
    },
  ],
}

const DRIVE_AND_KICK: Play = {
  id: 'demo-dk',
  name: 'Drive & Kick',
  keyframes: [
    {
      id: 'dk-1',
      description: 'Posición inicial. El 1 con el balón en la cima del arco, el 5 en el poste alto.',
      ballPosition: { x: 50, y: 72 },
      positions: [
        { playerId: 'o1', x: 50, y: 72 },
        { playerId: 'o2', x: 15, y: 55 },
        { playerId: 'o3', x: 85, y: 55 },
        { playerId: 'o4', x: 12, y: 36 },
        { playerId: 'o5', x: 50, y: 28 },
        { playerId: 'd1', x: 50, y: 65 },
        { playerId: 'd2', x: 15, y: 50 },
        { playerId: 'd3', x: 85, y: 50 },
        { playerId: 'd4', x: 15, y: 30 },
        { playerId: 'd5', x: 48, y: 22 },
      ],
    },
    {
      id: 'dk-2',
      description: 'El 1 penetra hacia la derecha. Los alas abren espacio hacia los corners.',
      ballPosition: { x: 62, y: 62 },
      positions: [
        { playerId: 'o1', x: 62, y: 62 },
        { playerId: 'o2', x: 10, y: 46 },
        { playerId: 'o3', x: 90, y: 46 },
        { playerId: 'o4', x: 10, y: 28 },
        { playerId: 'o5', x: 50, y: 26 },
        { playerId: 'd1', x: 60, y: 58 },
        { playerId: 'd2', x: 10, y: 42 },
        { playerId: 'd3', x: 80, y: 42 },
        { playerId: 'd4', x: 15, y: 26 },
        { playerId: 'd5', x: 52, y: 20 },
      ],
    },
    {
      id: 'dk-3',
      description: 'El 1 llega al fondo. El 3 está completamente abierto en el ala derecha.',
      ballPosition: { x: 72, y: 50 },
      positions: [
        { playerId: 'o1', x: 72, y: 50 },
        { playerId: 'o2', x: 8, y: 40 },
        { playerId: 'o3', x: 92, y: 40 },
        { playerId: 'o4', x: 8, y: 26 },
        { playerId: 'o5', x: 50, y: 24 },
        { playerId: 'd1', x: 65, y: 46 },
        { playerId: 'd2', x: 10, y: 36 },
        { playerId: 'd3', x: 86, y: 36 },
        { playerId: 'd4', x: 15, y: 22 },
        { playerId: 'd5', x: 52, y: 18 },
      ],
    },
    {
      id: 'dk-4',
      description: '¡Kick out al 3! Tiro abierto de tres. El defensor llega tarde.',
      ballPosition: { x: 94, y: 36 },
      positions: [
        { playerId: 'o1', x: 65, y: 44 },
        { playerId: 'o2', x: 8, y: 36 },
        { playerId: 'o3', x: 94, y: 36 },
        { playerId: 'o4', x: 8, y: 22 },
        { playerId: 'o5', x: 52, y: 20 },
        { playerId: 'd1', x: 60, y: 40 },
        { playerId: 'd2', x: 10, y: 32 },
        { playerId: 'd3', x: 90, y: 30 },
        { playerId: 'd4', x: 15, y: 20 },
        { playerId: 'd5', x: 55, y: 16 },
      ],
    },
  ],
}

const FAST_BREAK: Play = {
  id: 'demo-fb',
  name: 'Contraataque 3×2',
  keyframes: [
    {
      id: 'fb-1',
      description: 'Contraataque 3 vs 2. El 1 conduce al centro, el 2 y el 3 abren carriles por los laterales.',
      ballPosition: { x: 50, y: 70 },
      positions: [
        { playerId: 'o1', x: 50, y: 70 },
        { playerId: 'o2', x: 20, y: 62 },
        { playerId: 'o3', x: 80, y: 62 },
        { playerId: 'o4', x: 32, y: 80 },
        { playerId: 'o5', x: 68, y: 80 },
        { playerId: 'd1', x: 50, y: 82 },
        { playerId: 'd2', x: 28, y: 75 },
        { playerId: 'd3', x: 72, y: 75 },
        { playerId: 'd4', x: 36, y: 42 },
        { playerId: 'd5', x: 64, y: 42 },
      ],
    },
    {
      id: 'fb-2',
      description: 'Los defensores colapsan al centro. El 1 busca al compañero libre en las bandas.',
      ballPosition: { x: 50, y: 56 },
      positions: [
        { playerId: 'o1', x: 50, y: 56 },
        { playerId: 'o2', x: 12, y: 48 },
        { playerId: 'o3', x: 88, y: 48 },
        { playerId: 'o4', x: 32, y: 66 },
        { playerId: 'o5', x: 68, y: 66 },
        { playerId: 'd1', x: 50, y: 70 },
        { playerId: 'd2', x: 28, y: 62 },
        { playerId: 'd3', x: 72, y: 62 },
        { playerId: 'd4', x: 40, y: 38 },
        { playerId: 'd5', x: 60, y: 38 },
      ],
    },
    {
      id: 'fb-3',
      description: 'El 1 pasa al 3 en el ala derecha. El 5 ataca el aro por el centro.',
      ballPosition: { x: 88, y: 36 },
      positions: [
        { playerId: 'o1', x: 44, y: 46 },
        { playerId: 'o2', x: 10, y: 36 },
        { playerId: 'o3', x: 88, y: 36 },
        { playerId: 'o4', x: 32, y: 55 },
        { playerId: 'o5', x: 56, y: 28 },
        { playerId: 'd1', x: 50, y: 56 },
        { playerId: 'd2', x: 25, y: 50 },
        { playerId: 'd3', x: 75, y: 50 },
        { playerId: 'd4', x: 44, y: 30 },
        { playerId: 'd5', x: 82, y: 30 },
      ],
    },
    {
      id: 'fb-4',
      description: '¡El 3 pasa al 5 que está solo bajo el aro! Bandeja fácil. El defensor llega tarde.',
      ballPosition: { x: 50, y: 16 },
      positions: [
        { playerId: 'o1', x: 42, y: 40 },
        { playerId: 'o2', x: 8, y: 30 },
        { playerId: 'o3', x: 86, y: 30 },
        { playerId: 'o4', x: 32, y: 48 },
        { playerId: 'o5', x: 50, y: 16 },
        { playerId: 'd1', x: 48, y: 48 },
        { playerId: 'd2', x: 22, y: 42 },
        { playerId: 'd3', x: 74, y: 42 },
        { playerId: 'd4', x: 48, y: 26 },
        { playerId: 'd5', x: 80, y: 24 },
      ],
    },
  ],
}

const ZONE_ATTACK: Play = {
  id: 'demo-zone',
  name: 'Ataque Zona 2-3',
  keyframes: [
    {
      id: 'zone-1',
      description: 'Ataque a zona 2-3. El 1 con el balón en la cima, el 5 hace un flash al poste medio.',
      ballPosition: { x: 50, y: 72 },
      positions: [
        { playerId: 'o1', x: 50, y: 72 },
        { playerId: 'o2', x: 22, y: 60 },
        { playerId: 'o3', x: 78, y: 60 },
        { playerId: 'o4', x: 18, y: 38 },
        { playerId: 'o5', x: 50, y: 32 },
        { playerId: 'd1', x: 36, y: 46 },
        { playerId: 'd2', x: 64, y: 46 },
        { playerId: 'd3', x: 20, y: 28 },
        { playerId: 'd4', x: 50, y: 24 },
        { playerId: 'd5', x: 80, y: 28 },
      ],
    },
    {
      id: 'zone-2',
      description: 'Pase al 2 en el ala izquierda. Toda la zona se desplaza hacia ese lado.',
      ballPosition: { x: 18, y: 58 },
      positions: [
        { playerId: 'o1', x: 50, y: 70 },
        { playerId: 'o2', x: 18, y: 58 },
        { playerId: 'o3', x: 82, y: 56 },
        { playerId: 'o4', x: 12, y: 36 },
        { playerId: 'o5', x: 50, y: 30 },
        { playerId: 'd1', x: 24, y: 46 },
        { playerId: 'd2', x: 58, y: 44 },
        { playerId: 'd3', x: 15, y: 28 },
        { playerId: 'd4', x: 50, y: 24 },
        { playerId: 'd5', x: 82, y: 28 },
      ],
    },
    {
      id: 'zone-3',
      description: 'Swing rápido al 3 en el ala derecha. ¡La zona está desbalanceada y tarda en reaccionar!',
      ballPosition: { x: 85, y: 54 },
      positions: [
        { playerId: 'o1', x: 50, y: 68 },
        { playerId: 'o2', x: 18, y: 56 },
        { playerId: 'o3', x: 85, y: 54 },
        { playerId: 'o4', x: 12, y: 34 },
        { playerId: 'o5', x: 50, y: 28 },
        { playerId: 'd1', x: 34, y: 46 },
        { playerId: 'd2', x: 68, y: 44 },
        { playerId: 'd3', x: 18, y: 28 },
        { playerId: 'd4', x: 50, y: 24 },
        { playerId: 'd5', x: 80, y: 26 },
      ],
    },
    {
      id: 'zone-4',
      description: '¡El 3 encuentra al 5 en el boquete de la zona! Tiro cómodo cerca del aro.',
      ballPosition: { x: 50, y: 22 },
      positions: [
        { playerId: 'o1', x: 50, y: 66 },
        { playerId: 'o2', x: 15, y: 52 },
        { playerId: 'o3', x: 85, y: 52 },
        { playerId: 'o4', x: 10, y: 30 },
        { playerId: 'o5', x: 50, y: 22 },
        { playerId: 'd1', x: 30, y: 44 },
        { playerId: 'd2', x: 70, y: 44 },
        { playerId: 'd3', x: 18, y: 26 },
        { playerId: 'd4', x: 50, y: 26 },
        { playerId: 'd5', x: 82, y: 26 },
      ],
    },
  ],
}

export const DEMO_PLAYS: Play[] = [
  PICK_AND_ROLL,
  DRIVE_AND_KICK,
  FAST_BREAK,
  ZONE_ATTACK,
]
